monday_morning:
  run_length_min: 99.0
  suggested_barista_count: 3
  arrival_rate_per_hour: 61.212121212121204
  poisson_lambda_per_minute: 1.02020202020202
  p_drink: 0.24752475247524752
  empirical_interarrivals_min:
  - 0.0
  - 1.0
  - 2.0
  - 1.0
  - 2.0
  - 0.0
  - 0.0
  - 2.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 4.0
  - 0.0
  - 2.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 2.0
  - 0.0
  - 1.0
  - 2.0
  - 1.0
  - 0.0
  - 2.0
  - 1.0
  - 4.0
  - 0.0
  - 0.0
  - 0.0
  - 3.0
  - 1.0
  - 2.0
  - 2.0
  - 3.0
  - 0.0
  - 1.0
  - 2.0
  - 0.0
  - 2.0
  - 1.0
  - 1.0
  - 0.0
  - 2.0
  - 1.0
  - 6.0
  - 0.0
  - 0.0
  - 1.0
  - 2.0
  - 4.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 2.0
  - 4.0
  - 1.0
  - 0.0
  - 2.0
  - 4.0
  - 0.0
  - 2.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  empirical_service_drink_min:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  empirical_service_food_min:
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 4.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 3.0
  - 4.0
  - 2.0
  - 4.0
  - 3.0
  - 3.0
  - 4.0
  - 3.0
  - 3.0
  - 3.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 3.0
  - 2.0
  - 2.0
  - 3.0
  - 3.0
  - 4.0
  - 4.0
  - 3.0
  - 2.0
  - 3.0
  - 3.0
  - 5.0
  - 3.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 3.0
  - 3.0
  - 2.0
  - 3.0
  - 4.0
  - 3.0
  - 2.0
  - 4.0
  - 4.0
  - 2.0
  - 5.0
  - 3.0
  - 3.0
  - 3.0
  - 3.0
  - 2.0
  - 3.0
  - 2.0
monday_afternoon:
  run_length_min: 44.0
  suggested_barista_count: 4
  arrival_rate_per_hour: 120.0
  poisson_lambda_per_minute: 2.0
  p_drink: 0.5568181818181818
  empirical_interarrivals_min:
  - 0.0
  - 1.0
  - 2.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 2.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 3.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 3.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 2.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  empirical_service_drink_min:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  empirical_service_food_min:
  - 4.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 4.0
  - 4.0
  - 3.0
  - 3.0
  - 3.0
  - 3.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
monday_evening:
  run_length_min: 65.0
  suggested_barista_count: 2
  arrival_rate_per_hour: 48.92307692307692
  poisson_lambda_per_minute: 0.8153846153846154
  p_drink: 0.5283018867924528
  empirical_interarrivals_min:
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 2.0
  - 5.0
  - 0.0
  - 0.0
  - 2.0
  - 5.0
  - 0.0
  - 2.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  - 1.0
  - 3.0
  - 0.0
  - 4.0
  - 0.0
  - 3.0
  - 0.0
  - 1.0
  - 2.0
  - 2.0
  - 3.0
  - 0.0
  - 2.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 1.0
  - 2.0
  - 2.0
  - 1.0
  - 0.0
  - 0.0
  - 3.0
  - 1.0
  - 0.0
  empirical_service_drink_min:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  empirical_service_food_min:
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
  - 3.0
  - 2.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 3.0
tuesday_morning:
  run_length_min: 95.0
  suggested_barista_count: 1
  arrival_rate_per_hour: 52.42105263157895
  poisson_lambda_per_minute: 0.8736842105263158
  p_drink: 0.8674698795180723
  empirical_interarrivals_min:
  - 0
  - 0
  - 1
  - 2
  - 1
  - 1
  - 0
  - 2
  - 0
  - 1
  - 0
  - 2
  - 0
  - 1
  - 0
  - 6
  - 0
  - 1
  - 2
  - 1
  - 0
  - 1
  - 1
  - 3
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 1
  - 2
  - 1
  - 0
  - 0
  - 1
  - 0
  - 2
  - 1
  - 2
  - 1
  - 1
  - 0
  - 1
  - 2
  - 0
  - 1
  - 1
  - 0
  - 1
  - 1
  - 0
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 0
  - 1
  - 0
  - 1
  - 2
  - 1
  - 1
  - 1
  - 1
  - 0
  - 4
  - 0
  - 1
  - 0
  - 2
  - 1
  - 1
  - 0
  - 2
  - 1
  - 1
  - 1
  empirical_service_drink_min:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  empirical_service_food_min:
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
tuesday_afternoon:
  run_length_min: 73.0
  suggested_barista_count: 2
  arrival_rate_per_hour: 71.5068493150685
  poisson_lambda_per_minute: 1.1917808219178083
  p_drink: 0.7241379310344828
  empirical_interarrivals_min:
  - 0
  - 1
  - 2
  - 0
  - 2
  - 1
  - 1
  - 0
  - 0
  - 2
  - 1
  - 1
  - 1
  - 2
  - 2
  - 0
  - 2
  - 1
  - 0
  - 1
  - 0
  - 0
  - 2
  - 1
  - 0
  - 0
  - 1
  - 0
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 2
  - 1
  - 2
  - 0
  - 0
  - 1
  - 1
  - 0
  - 1
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
  - 1
  - 0
  - 1
  - 2
  - 0
  - 1
  - 1
  - 0
  - 2
  - 0
  - 1
  - 0
  - 0
  - 1
  - 0
  - 2
  - 0
  - 2
  - 1
  - 1
  - 2
  - 0
  - 0
  - 1
  - 0
  - 1
  - 2
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  empirical_service_drink_min:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  empirical_service_food_min:
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
tuesday_evening:
  run_length_min: 71.0
  suggested_barista_count: 2
  arrival_rate_per_hour: 49.014084507042256
  poisson_lambda_per_minute: 0.8169014084507042
  p_drink: 0.3620689655172414
  empirical_interarrivals_min:
  - 0
  - 1
  - 3
  - 0
  - 1
  - 1
  - 4
  - 3
  - 5
  - 1
  - 0
  - 0
  - 1
  - 1
  - 1
  - 2
  - 0
  - 0
  - 1
  - 2
  - 0
  - 1
  - 2
  - 2
  - 2
  - 0
  - 3
  - 1
  - 0
  - 2
  - 3
  - 1
  - 1
  - 2
  - 0
  - 2
  - 1
  - 0
  - 0
  - 0
  - 1
  - 1
  - 2
  - 1
  - 2
  - 5
  - 0
  - 2
  - 1
  - 0
  - 0
  - 1
  - 0
  - 1
  - 0
  - 1
  - 1
  - 2
  empirical_service_drink_min:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  empirical_service_food_min:
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 5.0
  - 5.0
  - 2.0
  - 3.0
  - 2.0
  - 3.0
  - 3.0
  - 2.0
  - 2.0
  - 3.0
  - 3.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 6.0
  - 3.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  - 3.0
  - 2.0
